import { Montserrat } from "next/font/google";
import "./globals.css";

const montse = Montserrat({ subsets: ["vietnamese"], weight: "700" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montse.className}>{children}</body>
    </html>
  );
}
