import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <Link href="/state">useState Page</Link>
          <Link href="/reducer">useReducer Page</Link>
          <Link href="/reducer-with-more-state">
            useReducer with more state Page
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
